package pojos;
// Generated 20 de febr. 2025, 16:13:19 by Hibernate Tools 6.1.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Club generated by hbm2java
 */
public class Club implements java.io.Serializable {

	private int codiClub;
	private String nomClub;
	private String comentari;
    private Set<Viatger> viatgers = new HashSet<>();

	public Club() {
	}

	public Club(int codiClub, String nomClub) {
		this.codiClub = codiClub;
		this.nomClub = nomClub;
	}

	public Club(int codiClub, String nomClub, String comentari, Set viatgers) {
		this.codiClub = codiClub;
		this.nomClub = nomClub;
		this.comentari = comentari;
		this.viatgers = viatgers;
	}

	public int getCodiClub() {
		return this.codiClub;
	}

	public void setCodiClub(int codiClub) {
		this.codiClub = codiClub;
	}

	public String getNomClub() {
		return this.nomClub;
	}

	public void setNomClub(String nomClub) {
		this.nomClub = nomClub;
	}

	public String getComentari() {
		return this.comentari;
	}

	public void setComentari(String comentari) {
		this.comentari = comentari;
	}

	public Set<Viatger> getViatgers() {
        return this.viatgers;
    }

    public void setViatgers(Set<Viatger> viatgers) {
        this.viatgers = viatgers;
    }

}
