package pojos;
// Generated 20 de febr. 2025, 16:13:19 by Hibernate Tools 6.1.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Ruta generated by hbm2java
 */
public class Ruta implements java.io.Serializable {

	private Integer codiRuta;
	private String nom;
	private String origen;
	private String desti;
	private Set<Viatger> viatgers = new HashSet<>();

	public Ruta() {
	}

	public Ruta(String nom) {
		this.nom = nom;
	}

	public Ruta(String nom, String origen, String desti, Set viatgers) {
		this.nom = nom;
		this.origen = origen;
		this.desti = desti;
		this.viatgers = viatgers;
	}

	public Integer getCodiRuta() {
		return this.codiRuta;
	}

	public void setCodiRuta(Integer codiRuta) {
		this.codiRuta = codiRuta;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getOrigen() {
		return this.origen;
	}

	public void setOrigen(String origen) {
		this.origen = origen;
	}

	public String getDesti() {
		return this.desti;
	}

	public void setDesti(String desti) {
		this.desti = desti;
	}

	public Set<Viatger> getViatgers() {
		return viatgers;
	}

	public void setViatgers(Set<Viatger> viatgers) {
		this.viatgers = viatgers;
	}

	@Override
    public String toString() {
        return "Ruta{" +
                "codiRuta=" + codiRuta +
                ", nom='" + nom + '\'' +
                ", origen='" + origen + '\'' +
                ", desti='" + desti + '\'' +
                ", viatgers=" + (viatgers != null ? viatgers.size() : 0) +
                '}';
    }
}
