package pojos;
// Generated 20 de febr. 2025, 16:13:19 by Hibernate Tools 6.1.7.Final

/**
 * Viatger generated by hbm2java
 */
public class Viatger implements java.io.Serializable {

	private String dni;
	private Club club;
	private Ruta ruta;
	private String cognoms;
	private String nom;
	private String tlf;

	public Viatger() {
	}

	public Viatger(String dni, Club club, Ruta ruta, String cognoms, String nom) {
		this.dni = dni;
		this.club = club;
		this.ruta = ruta;
		this.cognoms = cognoms;
		this.nom = nom;
	}

	public Viatger(String dni, Club club, Ruta ruta, String cognoms, String nom, String tlf) {
		this.dni = dni;
		this.club = club;
		this.ruta = ruta;
		this.cognoms = cognoms;
		this.nom = nom;
		this.tlf = tlf;
	}

	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	public Club getClub() {
		return this.club;
	}

	public void setClub(Club club) {
		this.club = club;
	}

	public Ruta getRuta() {
		return this.ruta;
	}

	public void setRuta(Ruta ruta) {
		this.ruta = ruta;
	}

	public String getCognoms() {
		return this.cognoms;
	}

	public void setCognoms(String cognoms) {
		this.cognoms = cognoms;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getTlf() {
		return this.tlf;
	}

	public void setTlf(String tlf) {
		this.tlf = tlf;
	}

}
